[tool.black]
line-length = 120
target-version = ['py313']

[tool.ruff]
line-length = 120
target-version = "py313"
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "BLE001", "COM812"]

[tool.ruff.lint.isort]
combine-as-imports = true