[tool.black]
line-length = 120
target-version = ['py313']

[tool.ruff]
line-length = 120
target-version = "py313"
select = ["ALL"]
ignore = ["D", "TRY003"]  # ignora docstrings
fix = true
show-fixes = true

[tool.ruff.isort]
known-first-party = ["seu_pacote"]
combine-as-imports = true