name: Publish Release

on:
  workflow_call:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: file-watcher-mover-win64
          path: ./

      - name: Extract version from branch name
        id: version
        run: |
          # Extrai versão da branch release/x.x.x
          VERSION="${{ github.head_ref }}"
          VERSION=$(echo $VERSION | sed 's/release\///')
          
          # Valida se está no formato x.x.x
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Branch name should follow pattern release/x.x.x, got: ${{ github.head_ref }}"
            exit 1
          fi
          
          # Adiciona o 'v' prefix para a tag
          VERSION="v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version extracted: $VERSION"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Changes
            
            Release criada automaticamente a partir da branch `${{ github.head_ref }}`.
            
            ### Downloads
            - **file-watcher-mover-win64.zip**: Executável para Windows 64-bit
            
            ### Como usar
            1. Baixe o arquivo `file-watcher-mover-win64.zip`
            2. Extraia em uma pasta de sua escolha
            3. Configure o arquivo `config.json` conforme necessário
            4. Execute `file-watcher-mover-win64.exe`
          draft: false
          prerelease: false
          files: ./file-watcher-mover-win64.zip