name: Lint and Format Check
on:
  workflow_call:

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install black

      - name: Check Ruff (lint + isort)
        run: ruff check .

      - name: Check Black formatting
        run: black . --check